name: GitHub Action Documentation
author: "@katydecorah"
description: "A GitHub action to help document your GitHub action."
runs:
  using: "node16"
  main: dist/index.js

inputs:
  example-workflow-file:
    description: The example workflow file in `.github/workflows/`
    default: example.yml
  additional-workflow-file-prefix:
    description: To include additional workflow files, save them with this prefix in `.github/workflow/`.
    default: example
  documentation-file:
    description: The file where the action will write and update documentation for the action.
    default: README.md
