name: Document GitHub action (advanced)
# This workflow file is the same as example.yml
# It's a proof of concept that you provide additional workflow files and they will appear in the README.

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/example-advanced.yml"
      - "action.yml"
      - "package.json"
      - "README.md"

jobs:
  document_action:
    runs-on: ubuntu-latest
    name: Write documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Documentation action
        id: documentation
        uses: ./
      - name: Commit files
        if: steps.documentation.outputs.update == 'true'
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update documentation"
          git push
